stackbuilders/react-native-spotlight-tour

.circleci/config.yml
We're missing a dependency in the tags filter of the workflow. The `release` job depends on the `build` job and only runs when a tag is pushed. Therefore, the `build` job needs a filter for tags in order to kick off the workflow.
Docs: https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag
=> [CircleCI] Fix release job dependencies

.circleci/config.yml
We cannot install NPM with the `circleci/node` orb if we're using a Node image. Since the image already has NPM installed, the orb step fails
=> [CircleCI] Fix NPM issue

example/README.md, example/package.json, package.json
In the file whitelist, NPM will not recognize the format `./dist/`, so we need to change it to `dist/`
=> fix(release): NPM issue with whitelist format

README.md, example/App.tsx
The `README.md` file still contains old information on how to install the library. All references were updated to `@stackbuilders/react-native-spotlight-tour` to match NPMs registry
=> Chore(docs): Update readme

example/android/build.gradle
This PR pushes the file `gradlew.bat` of the sample with the correct line ending for Windows files (CRLF). In addition, I added a change in the `build.gradle` file to preserve the distribution the of the Gradle Wrapper whenever we update/change it 🙂
=> chore(example): Fix gradlew.bat line ending

example/yarn.lock, package.json, src/lib/AttachStep.component.tsx, test/index.test.tsx, test/lib/tour-overlay/TourOverlay.component.test.tsx, yarn.lock
This PR fixes an issue when attaching a step to function components. The problem is that we were relying on the children's ref to measure the size of the component and to get its position on the screen. However, function components do not have a ref unless they are created with `React.forwardRef(..)`. Since we don't really have control over how the children are going to be created, it's a better idea to just wrap the attached component in a `View` that will take the same size as the children and use its ref to make the measures. We were already doing this when more than one component was passed in the children of `AttachStep`.
=> fix(attach-step): Fix attach to function components

example/yarn.lock, src/lib/AttachStep.component.tsx, src/lib/SpotlightTour.context.ts, src/lib/SpotlightTour.provider.tsx, src/lib/tour-overlay/TourOverlay.component.tsx, test/index.test.tsx, test/lib/tour-overlay/TourOverlay.component.test.tsx
This PR fixes a few issues present in the `AttachStep` component. The most relevant of them is that the component was using a `View` to wrap its children (the attached step component), which allowed (or prevented) styling this view, causing issues with the resulting measures for the spotlight width and height.
The `AttachStep` component should not be considered something that renders on the screen. Instead, this is a transient component used to mark something as one of the steps of the tour. Users should do styling on the children of `AttachStep` to achieve the desired behavior.
=> fix(core): AttachStep issues

example/metro.config.js, example/metro.config.ts, example/src/App.tsx, example/yarn.lock, package.json, src/lib/AttachStep.component.tsx, src/lib/SpotlightTour.context.ts, src/lib/SpotlightTour.provider.tsx, src/lib/tour-overlay/TourOverlay.component.tsx, src/lib/tour-overlay/TourOverlay.styles.ts, test/index.test.tsx
This PR refactors the animation flow of the tour to fix the issues when running the animations on the native threads on both iOS and Android. In a nutshell, the problem was that the first animation was trying to start before both the Overlay and the SVG components were rendered. This caused a problem when `useNativeDriver: true` was set on the animation, causing the first spotlight to not appear on iOS, and the tour to crash on Android.
Additionally, a new prop was added to the `<SpotlightTourProvider />` component so users can choose to enable/disable animation on the native thread based on the OS. Some other changes on this PR includes:
- Fix the example `metro.config.js` file, as the .ts file was not being recognized
- Improve `yarn dev` command to start the example bundler at the end …
=> perf(core): Refactor animation flow

.github/workflows/ci.yml, .github/workflows/pages.yml, .github/workflows/release.yml, .releaserc.json, package.json, yarn.lock
This PR refactors the release.yml workflow to be triggered on a push to the `release` branch. At the same time, we reuse the `ci.yml` workflow as a requirement for the `deploy:` job.
**Pipeline Test:** https://github.com/stackbuilders/react-native-spotlight-tour/actions/runs/3439395566
**Reference:** https://docs.github.com/en/actions/using-workflows/reusing-workflows
=> chore(ci): Refactor release workflow

.eslintrc.json, package.json, src/lib/SpotlightTour.context.ts, src/lib/SpotlightTour.provider.tsx, src/lib/components/tour-overlay/TourOverlay.component.tsx, test/helpers/TestTour.tsx, test/helpers/helper.ts, test/helpers/nativeMocks.ts, test/lib/tour-overlay/TourOverlay.component.test.tsx, test/setup.ts, yarn.lock
This PR aims to improve the ESLint rules and configuration to improve development practices and increase static check standards. It also turns off specific rules on `test` and `typetest` files which makes sense to no apply in those specific cases.
=> chore(lint): Improve ESLint rules

example/src/App.tsx, package/src/lib/SpotlightTour.context.ts, package/src/lib/SpotlightTour.provider.tsx, package/test/integration/index.test.tsx, package/test/integration/lib/tour-overlay/TourOverlay.component.test.tsx
This PR adds the possibility to run some events or actions after the tour stops by adding a new prop to the SpotLightTourProvider called onStop.
It solves issue #89
=> feat(core): Add onStop callback to SpotLightTourProvider props

example/src/App.tsx, package/package.json, package/src/lib/SpotlightTour.context.ts, package/src/lib/SpotlightTour.provider.tsx, package/src/lib/components/tour-overlay/TourOverlay.component.tsx, package/src/lib/components/tour-overlay/shapes/CircleShape.component.tsx, yarn.lock
This PR fixes a few tooltip issues. The main one was that the tooltip view was rendered within the `CircleShape` component, so the overlay was always on top of the tooltip, and it was not possible to interact with it.
=> fix(core): Tooltip issues

README.md, example/package.json, example/src/App.tsx, example/src/DocsTooltip.tsx, package.json, package/package.json, yarn.lock
BREAKING CHANGE: This package has been renamed `react-native-spotlight-tour` to make its usage more straightforward and explicit. This change also helps build tools and exclusion patterns, making it easier to be part of regular expressions that aim to exclude or transform all react-native packages (e.g., working with react-native-web).
=> feat(package): Rename package to react-native-spotlight-tour

.github/workflows/release.yml, package.json, package/.releaserc.json, package/package.json, yarn.lock
This PR updates the release workflow to improve semantic-release work with yarn workspaces. It also drops the usage of the `release` branch and makes things smoother by using the `main` branch and allowing on-demand dispatch of the release.yml workflow whenever we need to release.
=> chore(release): Update release workflow

package/typedoc.json
👋 Hey, I have fixed the issue #129 by editing the `package/typedoc.json` file. 🚀
As part of [Stack Builders Inc.](https://www.stackbuilders.com/) Hacktoberfest 2023 event.
=> docs(typedoc): Fix Docs Broken Url

example/src/App.tsx, package/package.json, package/src/helpers/common.ts, package/src/lib/SpotlightTour.context.ts, package/src/lib/SpotlightTour.provider.tsx, package/src/lib/components/tour-overlay/TourOverlay.component.tsx, package/src/lib/components/tour-overlay/TourOverlay.styles.ts, package/src/main.ts, package/test/helpers/TestTour.tsx, yarn.lock
BREAKING CHANGE: The tooltip arrow now renders by default. FloatingUI-related props were refactored.
The `middleware` prop was removed, now you can either pass each supported middleware options or a boolean to enable/disable the feature controlled by each middleware.
=> feat!(tooltip): Add tooltip arrow

example/metro.config.web.cjs, example/package.json, yarn.lock
=> Fix: web:build command not longer throw errors

package/src/lib/SpotlightTour.context.ts, package/src/lib/SpotlightTour.provider.tsx, package/src/lib/components/tour-overlay/TourOverlay.component.tsx, package/src/main.ts
BREAKING CHANGE: Making the shape configurable also removes the `spotPadding` prop from the SpotlightTourProvider. The padding can now be configured in the `shape` prop of the SpotlightTourProvider or independently on each step configuration.
=> feat!(shape): Make shape configurable

package/src/lib/components/attach-step/AttachStep.component.tsx, package/test/integration/lib/tour-overlay/TourOverlay.component.test.tsx
Hello! 
Sorry for proposing this feature directly as a Pull Request, but I needed it for my own Tour and thought it would be nice to contribute to the project :)
Let me know what you think and how we can make it better!
=> feat(core): Allow multiple indexes in a single AttachStep

package/src/lib/components/tour-overlay/TourOverlay.component.tsx
This PR resolves #169
**Changes:**
* Modal needed `supportedOrientations` to set orientations for iOS. Adding landscape and portrait modal support.
* SVG spot and overlay must be set to the total screen width and height properly on window size changes or rotations.
=> fix(core): Tour overlay modal dimension changes
